FROM jenkins/jenkins:lts
MAINTAINER Mariusz Karpiarz

USER root
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

# Skip the post-install wizard
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
