== Django container usage
To build a container with a specific Django version modify `requirements.txt` in the project directory.

You can also build the container using a different directory entirely where you can have your own `requirements.txt`:

-------
$ docker build --build-arg PROJECT_DIR=<path-to-your-dir> . -t <name:tag>
-------

== Running the app
First, run the database container:

-------
$ docker run -d --name postgres -e POSTGRES_USER=django -e POSTGRES_PASSWORD_FILE=/opt/postgres_pass -v $(pwd)/postgres_pass:/opt/postgres_pass -v <dir-to-store-pgdata>:/var/lib/postgresql/data postgres:10
-------
To run the app, first create a container off of the newly built image by running:

-------
$ docker run --name app -dit -p 8000:8000 $(pwd):/opt/app --link postgres:db <name:tag> /bin/bash
-------
When inside the container, move to the directory with the app and run the dev server:

-------
# cd /opt/app/podcastmanager/
# python manage.py runserver 0.0.0.0:8000
-------

=== Web server proxy
Instead of using Django's dev server, you can use nginx to proxy request to the app run with gunicorn.

Launch an nginx container and link it to the app container:

-------
$ docker run -d --name web -p 80:80 -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf:ro -v $(pwd)/podcastmanager/static/:/usr/share/nginx/html/static/:ro --link app:app nginx:1.15
-------
Inside the app container first collect static files:

-------
# cd /opt/app/podcastmanager/
# python manage.py collectstatic
-------
then run `gunicorn`:

-------
# gunicorn podcastmanager.wsgi -b 0.0.0.0:8000
-------
API will now be available under http://localhost/.

Bear in mind that nginx container is responsible for serving static files, so they won't be available when contacting the app container through its exposed port.

[NOTE]
====
The Docker image with for the app has supervisor configured to run gunicorn inside, so instead of running the container interactively, you can just let it use its default entrypoint command by executing:

-------
$ docker run --name app -d $(pwd):/opt/app --link postgres:db <name:tag>
-------
====

== Vault
First download and install HashiCorp Vault. Link:
https://www.vaultproject.io/downloads.html

Run Vault Docker container in server mode:

-------
$ docker run -d --cap-add=IPC_LOCK --name=vault -p 8200:8200 -v $(pwd)/vault/config/:/vault/config/ -v <host-dir-for-vault-data>:/vault/data/ vault:0.10.4 server
-------
If the data directory is empty, initialise Vault:

-------
$ export VAULT_ADDR=http://127.0.0.1:8200
$ vault init
-------
Write down unseal keys and the root token and store them somewhere safe.

Unseal Vault by running:

-------
$ vault unseal
-------
and specifying 3 of the unseal keys.

Next, log in as root by running:

-------
$ vault login
-------
and specifying the initial root token.

Instead of using this initial token, create a child one with:

-------
$ vault token create
-------
and re-login with the newly generated token.

Enable AppRole, add its policy and get role ID:

-------
$ vault auth enable approle
$ vault policy write ci-cd vault/ci-cd-policy.hcl
$ vault write auth/approle/role/ci-cd secret_id_ttl=60m token_ttl=60m token_max_tll=120m policies="ci-cd"
$ export ROLE_ID=$(vault read --field=role_id auth/approle/role/ci-cd/role-id)
-------

Add your secret by creating `dockerhub-secret.json` file with the following content:

-------
{
    "user": "<your-dockerhub-username>",
    "pass": "<your-dockerhub-password>"
}
-------
enable kv store and put the secret in vault:

-------
$ vault secrets enable kv
$ vault write kv/dockerhub @dockerhub-secret.json
-------
Dispose of or override the original file.

Add policy for Jenkins to allow it to generate secret IDs and get the main (long-lived) Jenkins token:

-------
$ vault policy write jenkins vault/jenkins-policy.hcl
$ export VAULT_TOKEN=$(vault token create --field=token -policy=jenkins)
-------
Store this token somewhere safe for future use.

Finally, generate a short-lived (valid for an hour) token for use in Jenkins jobs:

-------
$ ./token_generate_jenkins.sh ci-cd $ROLE_ID
-------
After this is run the token will be in `vault_token`.

== CI/CD
To build Jenkins image with plugins backed into it, run:

-------
$ docker build . -f Dockerfile.jenkins -t <name:tag>
-------
Create a volume for Jenkins (this is so Jenkins can share workspace with containers based off of images it builds):

-------
$ docker volume create jenkins-data
-------

Run the Jenkins container with:

-------
$ docker run -d --name jenkins -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker -v jenkins-data:/var/jenkins_home <name:tag>
-------
Now you can use Docker on the host from inside the Jenkins container.

=== Accessing Vault secrets in Jenkins
First, add Vault credentials in Jenkins by going to `Jenkins > Credentials > System > Global credentials (unrestricted) > Add Credentials` and specify the following:

____
Kind: Vault Token File Credential

Path to file containing token: /opt/app/vault_token

ID: vault

Description: Vault-Token
____

On the host run the script generating short-lived Jenkins token:

-------
$ ./token_generate_jenkins.sh ci-cd $ROLE_ID
-------
(make sure long-lived Jenkins token is set in `$VAULT_TOKEN` and the role ID is in `$ROLE_ID`)

Now you can use the credentials in the HashiCorp Vault Jenkins plugin by referring to them using their ID.

[NOTE]
====
Remember to regenerate the short-lived token when it expires.
====

=== Adding Jenkins plugins
To install a new Jenkins plugin, add its short name to the `plugins.txt` file, then build the Jenkins image and run a temporary container:

-------
$ docker run --rm <name:tag>
-------
If the plugin has prerequisites, they'll be listed on the output. Simply add the requirement to the list of plugins and rebuild the image.

== API Reference

-------
GET /v1/podcasts
-------
Retrieves a list of all podcasts.

Add `?format=json` or `.json` at the end to get output formatted in JSON.


-------
POST /v1/podcasts
{
    "name": "A podcast",
    "url": "http://example.com"
}
-------
Adds a podcast.

Parameters:

* *name* (required) - the name of the podcast
* *url* (required) - URL of this podcast's feed
