kind: ReplicationController
apiVersion: v1
metadata:
  name: db
spec:
  replicas: 1
  selector:
    app: db
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:10
        env:
        - name: POSTGRES_USER
          value: "django"
        - name: POSTGRES_PASSWORD_FILE
          value: "/opt/postgres_pass"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /opt/postgres_pass
          name: postgres-vol
          subPath: postgres_pass
          readOnly: true
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
          subPath: postgres_data
      volumes:
      - name: postgres-vol
        glusterfs:
          endpoints: glusterfs-cluster
          path: gluster
